#!/bin/bash
# Step 5: Verify - re-run audits after changes

echo "=== STEP 5: VERIFICATION ==="
echo ""
echo "After you apply the prescriptions from Step 4, run this:"
echo ""
echo "# Re-run location audit"
echo "cd .."
echo "./tools/geo-kernel/target/release/geo-kernel.exe audit . 23.0366 72.5615 > research/verify_location_after.txt"
echo ""
echo "# Re-run citation audit (requires OPENROUTER_API_KEY)"
echo "export OPENROUTER_API_KEY=<your-key>"
echo "python citation_audit.py  # writes citation_audit.md"
echo ""
echo "# Compare before/after"
echo "python research/step5_compare.py"
echo ""
echo "Expected improvements:"
echo "  ✓ Geo-kernel: all NAP fields have exactly 1 value (not 3-4 variants)"
echo "  ✓ All coordinates same-L16 cell (Gota resolved)"
echo "  ✓ citation_audit: 'entity_clear' scores go from 0.2-0.5 → 0.8-1.0"
echo "  ✓ 'answers_first' goes from 0.3-0.6 → 0.7-1.0 for priority pages"
echo "  ✓ 'OK' count increases from 2/37 → 10-15/37"
